services:
  ia_postgres_pgvector:
    image: pgvector/pgvector:0.7.4-pg16
    container_name: pgvector
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - .data/pg/data:/var/lib/postgresql/data
      - .data/pg:/docker-entrypoint-initdb.d
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - .data/ollama/data:/root/.ollama
